project:
  type: website

website:
  title: "Duster Renault 1.6 - 2015"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: ficha-tecnica.qmd
        text: Ficha tecnica
      - href: mantenimiento.qmd
        text: Mantenimiento
      - href: niveles-neumaticos.qmd
        text: Niveles y neumaticos
      - href: fuentes.qmd
        text: Fuentes

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    lang: es
